;/*=========== Summer Begin ===========;*/

	{"___FINLAND SUMMER__________________"
		{models
			{"dummygrass"}
		}
		{density 0.01}
	}
	
	{"fin_grass_short"
		{models
 			{"finland_grass_short1"}
 			{"finland_grass_short2"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	
	{"fin_grass_weeds"
		{models
 			{"finland_grass_short1"}
 			{"finland_grass_short2"}
 			{"finland_grass_weeds"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"fin_grass_weeds2"
		{models
 			{"finland_grass_weeds"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"fin_twigs"
		{models
 			{"finland_grass_tall1" "bare"}
 			{"finland_grass_tall2" "bare"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"___FINLAND WINTER__________________"
		{models
			{"dummygrass"}
		}
		{density 0.01}
	}
	{"fin_grass_win_dry"
		{models
 			{"finland_grass_short3"}
 			{"finland_grass_short4"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"fin_twigs_win"
		{models
 			{"finland_grass_tall1" "winter"}
 			{"finland_grass_tall2" "winter"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	
;/*=========== Spring End ===========;*/