;/*=========== Summer Begin ===========;*/

	{"___WEST SUMMER__________________"
		{models
			{"dummygrass"}
		}
		{density 0.01}
	}
	
	{"euro_grass_short"
		{models
 			{"grass_euro_short1"}
 			{"grass_euro_short2"}
			{"grass_euro_short1" "1"}
			{"grass_euro_short2"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_short_flower"
		{models
 			{"grass_euro_short1"}
 			{"grass_euro_short2"}
			{"grass_euro_short1" "1"}
			{"grass_euro_short1" "flower"}
			{"grass_euro_short2" "flower"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_short2"
		{models
			{"grass_euro_medium1" "2"}
			{"grass_euro_medium2" "2"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_medium"
		{models
 			{"grass_euro_medium1"}
 			{"grass_euro_medium2"}
			{"grass_euro_medium1" "1"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_medium_flower"
		{models
 			{"grass_euro_medium1"}
 			{"grass_euro_medium2"}
			{"grass_euro_medium1" "1"}
			{"grass_euro_medium1" "flower"}
			{"grass_euro_medium2" "flower"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_long"
		{models
 			{"grass_euro_long1"}
			{"grass_euro_long2"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_wild"
		{models
 			{"grass_euro_short2" "flower"}
			{"grass_euro_short1" "1"}
			{"grass_euro_short2"}
			{"grass_euro_wild1" "flower"}
			{"grass_euro_wild2" "flower"}
			{"grass_euro_wild1"}
			{"grass_euro_wild2"}
 			{"grass_euro_bush"}
 			{"grass_euro_long1" 0.25}
			{"grass_euro_long2" 0.25}
			{"grass_euro_long1" "flower" 0.25}
			{"grass_euro_long2" "flower" 0.25}
 			{"grass_euro_wild3" 0.05}
			{"grass_euro_wild4" 0.05}
 			{"grass_euro_thicket1" 0.2}
			{"grass_euro_thicket2" 0.2}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_nettle"
		{models
 			{"grass_euro_nettle1"}
			{"grass_euro_nettle2"}
			{"grass_euro_nettle3"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_nettle2"
		{models
 			{"grass_euro_nettle1"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_meadow"
		{models
 			{"grass_euro_meadow1"}
			{"grass_euro_meadow2"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_thicket"
		{models
 			{"grass_euro_thicket1"}
			{"grass_euro_thicket2"}
			{"grass_euro_thicket2" "1"}
		}
		{density 1}
	}
	{"euro_wheat"
		{models
 			{"grain_01"}
			{"grain_01a"}
		}
		{density 1}
	}	

;/*=========== Summer End ===========;*/


;/*=========== Autumn Begin ===========;*/
	
	{"___WEST AUTUMN__________________"
		{models
			{"dummygrass"}
		}
		{density 0.01}
	}
	{"euro_dry"
		{models
 			{"finland_grass_tall1" "bare_euro"}
 			{"finland_grass_tall2" "bare_euro"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_short_aut"
		{models
 			{"grass_euro_short1" "aut"}
 			{"grass_euro_short2" "aut"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_short_flower_aut"
		{models
 			{"grass_euro_short1" "aut"}
 			{"grass_euro_short2" "aut"}
			{"grass_euro_short1" "flower_aut"}
			{"grass_euro_short2" "flower_aut"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_medium_aut"
		{models
 			{"grass_euro_medium1" "aut"}
 			{"grass_euro_medium2" "aut"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_medium_aut2"
		{models
 			{"grass_euro_medium1" "aut2"}
 			{"grass_euro_medium2" "aut2"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_medium_flower_aut"
		{models
 			{"grass_euro_medium1" "aut2"}
 			{"grass_euro_medium2" "aut2"}
			{"grass_euro_medium1" "flower_aut"}
			{"grass_euro_medium2" "flower_aut"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_long_aut"
		{models
			{"grass_euro_wild1" "aut"}
			{"grass_euro_wild2" "aut"}
			{"grass_euro_long1" "aut" 0.25}
			{"grass_euro_long2" "aut" 0.25}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_nettle_aut"
		{models
 			{"grass_euro_nettle1" "aut"}
			{"grass_euro_nettle2" "aut"}
			{"grass_euro_nettle3" "aut"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_thicket_aut"
		{models
 			{"grass_euro_thicket1" "aut"}
 			{"grass_euro_thicket1" "aut"}
			{"grass_euro_thicket2" "aut1"}
			{"grass_euro_thicket2" "aut1"}
		}
		{density 1}
	}
	{"euro_autlate"
		{models
 			{"grass_euro_thicket1" "aut"}
 			{"grass_euro_thicket1" "aut"}
			{"grass_euro_thicket2" "aut1"}
			{"grass_euro_thicket2" "aut1"}
 			{"grass_euro_medium1" "aut2"}
 			{"grass_euro_medium2" "aut2"}
 			{"grass_euro_nettle1" "aut"}
		}
		{density 1}
	}
	{"euro_wild_aut"
		{models
 			{"grass_euro_short2" "flower_aut"}
			{"grass_euro_medium1" "aut1"}
 			{"grass_euro_bush" "aut"}
 			{"grass_euro_thicket1" "aut"}
 			{"grass_euro_thicket1" "aut"}
			{"grass_euro_thicket2" "aut1"}
			{"grass_euro_thicket2" "aut1"}   
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_bush_aut"
		{models
			{"grass_euro_medium1" "aut1"}
			{"grass_euro_medium2" "aut1"}
 			{"grass_euro_bush" "aut"} 
		}
		{density 1}
		{positionOffset 0.8}
	}
;/*=========== Autumn End ===========;*/


;/*=========== Winter Begin ===========;*/
	
	{"___WEST WINTER__________________"
		{models
			{"dummygrass"}
		}
		{density 0.01}
	}
	{"euro_grass_win_dry"
		{models
 			{"finland_grass_short3" "win"}
 			{"finland_grass_short4" "win"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_grass_win_dry2"
		{models
 			{"finland_grass_short3"}
 			{"finland_grass_short4"}
 			{"finland_grass_short3" "win"}
 			{"finland_grass_short4" "win"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_twigs_win"
		{models
 			{"finland_grass_tall1" "winter"}
 			{"finland_grass_tall2" "winter"}
		}
		{density 1}
		{positionOffset 0.8}
	}
	{"euro_thicket_win"
		{models
 			{"grass_euro_thicket1" "win"}
			{"grass_euro_thicket2" "win"}
 			{"grass_euro_thicket1" "win0"}
			{"grass_euro_thicket2" "win0"}
		}
		{density 1}
	}
	{"euro_thicket_win2"
		{models
 			{"grass_euro_thicket1" "aut"}
 			{"grass_euro_thicket1" "aut"}
			{"grass_euro_thicket2" "aut1"}
			{"grass_euro_thicket2" "aut1"}
 			{"grass_euro_thicket1" "win0"}
			{"grass_euro_thicket2" "win0"}
		}
		{density 1}
	}
	{"euro_bush_win"
		{models
			{"grass_euro_medium1" "flower_win"}
			{"grass_euro_medium2" "flower_win"}
			{"grass_euro_medium1" "win"}
			{"grass_euro_medium2" "win"}
 			{"grass_euro_bush" "win"} 
		}
		{density 1}
		{positionOffset 0.8}
	}
;/*=========== Winter End ===========;*/